apiVersion: v1
kind: Pod
metadata:
  name: busybox-configmap-all-as-env
spec:
  containers:
    - name: busybox
      image: busybox
      command: [ "/bin/sh", "-c", "sleep 3600" ]
      envFrom:
        - configMapRef:
            name: test-configmap-env-files