---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: dev
  name: nginx-dev1
spec:
  containers:
    - image: nginx
      name: nginx-dev1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: dev
  name: nginx-dev2
spec:
  containers:
    - image: nginx
      name: nginx-dev2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: dev
  name: nginx-dev3
spec:
  containers:
    - image: nginx
      name: nginx-dev3
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: prod
  name: nginx-prod1
spec:
  containers:
    - image: nginx
      name: nginx-prod1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: prod
  name: nginx-prod2
spec:
  containers:
    - image: nginx
      name: nginx-prod2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---