apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
    - args:
        - /bin/sh
        - -c
        - sleep 3600;
      image: busybox
      name: busybox
  dnsPolicy: ClusterFirst
  restartPolicy: Never