apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-test
  resources:
    requests:
      storage: 5Gi